"""rename columns

Revision ID: 781a18569f1b
Revises: c7861b123afe
Create Date: 2020-02-07 15:45:30.584059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781a18569f1b'
down_revision = 'c7861b123afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food') as batch_op:
        batch_op.alter_column('food_count', new_column_name='count')
        batch_op.alter_column('food_price', new_column_name='price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food') as batch_op:
        batch_op.alter_column('price', new_column_name='food_price')
        batch_op.alter_column('count', new_column_name='food_count')
    # ### end Alembic commands ###
