"""rename food table

Revision ID: c73915abdb9e
Revises: 444f602d771f
Create Date: 2020-02-10 21:57:05.261353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73915abdb9e'
down_revision = '444f602d771f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.rename_table('food', 'products')

    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('food_name', new_column_name='product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.rename_table('products', 'food')

    with op.batch_alter_table('food') as batch_op:
        batch_op.alter_column('product_name', new_column_name='food_name')
    # ### end Alembic commands ###
